// Writes hooks/cat-pixels.ts from the sprite in scripts/cat-sprite.mjs: each
// frame as terminal cells (▀ half blocks, two pixels a cell), for terminals
// that show no pictures (VS Code). Run: node scripts/cat-pixels.mjs
import { writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { COLORS, FRAMES } from './cat-sprite.mjs'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const DEFAULT = 0x01000000

function cells(rows) {
  const width = rows[0].length
  const words = new Uint32Array(width * (rows.length / 2) * 3)
  const color = ch => (ch === '.' ? null : (COLORS[ch][0] << 16) | (COLORS[ch][1] << 8) | COLORS[ch][2])
  for (let r = 0; r < rows.length / 2; r++) {
    for (let x = 0; x < width; x++) {
      const top = color(rows[r * 2][x]), bottom = color(rows[r * 2 + 1][x]), k = (r * width + x) * 3
      if (top === null && bottom === null) words.set([0x20, DEFAULT, DEFAULT], k)
      else if (top === null) words.set([0x2584, bottom, DEFAULT], k)
      else words.set([0x2580, top, bottom ?? DEFAULT], k)
    }
  }
  return Buffer.from(words.buffer).toString('base64')
}

const first = FRAMES.idle
const lines = Object.entries(FRAMES).map(([name, rows]) => `  ${name}: '${cells(rows)}',`)
writeFileSync(
  `${root}/hooks/cat-pixels.ts`,
  `// Generated by scripts/cat-pixels.mjs from scripts/cat-sprite.mjs: do not edit.
// The cat as terminal cells (▀ half blocks, two pixels a cell), for terminals
// that show no pictures. The drawing is Lucian Roman's, all rights reserved.

export const CAT_COLUMNS = ${first[0].length}
export const CAT_ROWS = ${first.length / 2}

export const CAT_CELLS: Readonly<Record<string, string>> = {
${lines.join('\n')}
}
`,
)
console.log(Object.keys(FRAMES).join(' '), `${first[0].length}x${first.length / 2}`)
