// Writes hooks/cat-pixels.ts: the cat as terminal cells, for terminals that
// show no pictures (VS Code). Needs Playwright with a Chromium:
//   node scripts/cat-pixels.mjs [path/to/playwright] [path/to/chromium]
import { writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const [, , playwrightPath = 'playwright', chromiumPath] = process.argv
const { chromium } = await import(playwrightPath.startsWith('/') ? pathToFileURL(`${playwrightPath}/index.mjs`).href : playwrightPath)
const browser = await chromium.launch({ ...(chromiumPath ? { executablePath: chromiumPath } : {}), args: ['--allow-file-access-from-files'] })
const page = await browser.newPage()
await page.goto(pathToFileURL(`${root}/scripts/cat-pixels.html`).href)
const art = await page.evaluate(src => window.build(src), pathToFileURL(`${root}/assets/cat/source.png`).href)
await browser.close()

const lines = Object.entries(art.frames).map(([name, f]) => `  ${name}: '${f.cells}',`)
writeFileSync(
  `${root}/hooks/cat-pixels.ts`,
  `// Generated by scripts/cat-pixels.mjs from assets/cat/source.png: do not edit.
// The cat as terminal cells (▀ half blocks, two pixels a cell), for terminals
// that show no pictures. The drawing is Lucian Roman's, all rights reserved.

export const CAT_COLUMNS = ${art.columns}
export const CAT_ROWS = ${art.rows}

export const CAT_CELLS: Readonly<Record<string, string>> = {
${lines.join('\n')}
}
`,
)
mkdirSync(`${root}/docs`, { recursive: true })
const html = Object.entries(art.frames).map(([name, f]) => `<figure><img src="${f.preview}"><figcaption>${name}</figcaption></figure>`).join('')
writeFileSync(process.env.PREVIEW ?? '/dev/null', `<body style="background:#1e1e1e;color:#ccc;font:12px monospace;display:flex;gap:16px">${html}</body>`)
console.log(Object.keys(art.frames).join(' '), `${art.columns}x${art.rows}`)
